Project5
Damini212/fe-project pull request #2
Opened 2023-07-17 15:25 UTC by Damini212

2023-07-17 15:38 UTC, sirKevlar commented on src/App.jsx
> +    <div>
I think we can be more semantic with our choice of HTML tag here... Usually divs are used purely for styling.

2023-07-17 15:38 UTC, sirKevlar commented on src/App.jsx
> +  const [articles, setArticles] = useState([]);
As our app has a useEffect making an api call, loading state should start off as true

2023-07-17 15:38 UTC, sirKevlar commented on src/components/Article.jsx
> +  const [article, setArticle] = useState(null);
This loading state should be initialised as true

2023-07-18 13:43 UTC, NRMSMITH requested changes
Just rendering the body! :D

2023-07-18 13:43 UTC, NRMSMITH commented on src/components/Article.jsx
> +          </div>
You've not displayed the the body of the article - so no one can read it!

2023-07-18 14:59 UTC, mezzDavies approved these changes
Just a few small things to think about in the comments below but this is approved. You could consider extracting your loading into a separate component. Also adding the timestapm to the article (in a human readable format.
Finally [this](https://www.refactoringui.com/previews/labels-are-a-last-resort) might be of interest regarding the use of labels eg Topic or Author

2023-07-18 14:59 UTC, mezzDavies commented on src/App.jsx
> +import { Articles } from "./components/articles";
This needs to be a capital "A" for /articles

2023-07-18 14:59 UTC, mezzDavies commented on src/components/Navbar.jsx
> +    <div className="navbar">
There is a better tag to use here in a **nav** section 😉

2023-07-18 14:59 UTC, mezzDavies commented on src/App.jsx
> +            <Route path="/article/:article_id" element={<Article />}></Route>
Ideally the route should be "/articles/:article_id" - note the "s" on articles - this is then RESTful 👍

2023-07-18 15:24 UTC, merged